version: "3"

services:
  db:
    network_mode: host
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rootdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data:/var/lib/postgresql/data

  migrations:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_migrations
    depends_on:
      db:
        condition: service_healthy

  server:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_server
    depends_on:
      - migrations

  client:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_client
    depends_on:
      - server

volumes:
  data:
    driver: local
