version: "3"

services:
  db:
    network_mode: host
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rootdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - data-test:/var/lib/postgresql/data

  migrations:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_migrations
    depends_on:
      - db

  test:
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_test
    depends_on:
      - db

volumes:
  data-test:
    driver: local
